### ISSUE TITLE
Lấy toàn album ở MP3 Zing bị sót bài

### ISSUE THREAD

**Issue by siunhanu** [thangdc/Album-Downloader#17]
Chào anh, đầu tiên rất cảm ơn anh vì một phần mềm rất hữu ích. Mình dùng phiên bản 1.4.0.6 để tải toàn bộ album từ Zing MP3 thì lúc quét ban đầu nhận đủ bài nhưng khi chuyển qua tải về thì thiếu mất, ví dụ 100 bài thì bắt được 80 bài, 80 bài thì bắt được 67 bài, 20 bài thì bắt đủ.
Một ý kiến góp ý nhỏ gửi đến anh!

**Comment by thangdc** [comment]
ok, để mình kiểm tra thử, mà bạn có album nào có số lượng bài nhiều cỡ 100 bài thì gửi cho mình để mình check thử nha, thật ra tìm cũng sẽ có nhưng mà hơi mất thời gian

**Comment by thangdc** [comment]
Theo mô tả mình nghĩ là do một trong những link trong album bị lỗi nên chương trình không tải được, khi lúc lấy bài hát thì chương trình chỉ lấy tên trong danh sách nên lúc nào cũng đầy đủ, còn khi lấy bài hát thì lúc đó chương trình mới bắt đầu lấy link bài hát thực sự lúc đó nó danh sách lúc đầu và lúc này sẽ không giống nhau nữa, khắc phục bằng cách lấy lại bài hát thêm lần nữa.
