### ISSUE TITLE
Không lấy danh sách bài hát từ album trên chiasenhac.com

### ISSUE THREAD

**Issue by hoangviet1990** [thangdc/Album-Downloader#18]
Chào anh, trước tiên em cảm ơn anh về phần mềm. Về phần lỗi em có dùng phần tìm kiếm trên phần mềm để tìm album nhưng ko lấy bài hát từ album đó về được, em có thử của những site khác thì hoàn toàn bình thường chỉ có site chiasenhac.com là ko được. Mong anh sửa lỗi này nhé vì em rất thích tải nhạc từ chiasenhac.com

**Comment by thangdc** [comment]
ok, mình sẽ kiểm tra và thông báo kết quả cho bạn sau, cảm ơn bạn đã thông báo

**Comment by thangdc** [comment]
mình vừa kiểm tra, bạn thử thay đổi chất lượng bài hát trong phần cấu hình cho chiasenhac.com thử xem sao nhé, thông thường thì phần mềm sẽ lấy chất lượng bài hát trên chiasenhac.com là 320kbps, nhưng có thể album đó không có những bài hát có chất lượng như thế nên bạn không thấy được nhạc trên album đó, thử thay đổi xuống 128kbps thử xem sao nha, còn nếu muốn tải nhạc 500kbps hoặc looless thì bạn cần dùng tài khoản để thiết lập trước khi lấy bài hát.

![album-downloader-config](https://cloud.githubusercontent.com/assets/1168970/6884755/3e94839a-d62a-11e4-89db-51f1ed51d544.png)
