### ISSUE TITLE
Tùy chọn nghe trước các bài hát trong album được chọn

### ISSUE THREAD

**Issue by baokiemvotinh** [thangdc/Album-Downloader#2]
Mình nghĩ bạn nên làm thêm nút pause, stop, next trong quá trình nghe album thì tuyệt. Bên cạnh đó bạn nên cải tiến chức năng nghe thử sao cho có thể nghe trước tất cả những bài hát được đánh dấu

**Comment by thangdc** [comment]
Mình đã bổ sung tính năng nghe hết bài này sang bài khác rồi nhưng mà nó không có được ổn định, nên mình chưa thể bổ sung tính năng này được

**Comment by thangdc** [comment]
Hiện tại tính năng này đã không còn được hỗ trợ. Cảm ơn.
