### ISSUE TITLE
Lỗi trạng thái tải về bài hát

### ISSUE THREAD

**Issue by hoanghaqng** [thangdc/Album-Downloader#20]
Chào bạn, phần mềm của bạn rất hay nhưng khi chạy có một lỗi nhỏ như sau. Mình đang sử dụng Windows 8.1 nhưng khi tải về album thì có một số bài hát hiển thị trạng thái 0%, mặc dù kiểm tra thư mục tải xuống bài hát đã tải về hoàn tất.  Bạn test lại thử nhé, cảm ơn bạn!

**Comment by thangdc** [comment]
vâng cảm ơn bạn, mình sẽ kiểm tra lại

**Comment by thangdc** [comment]
Mình thấy vấn đề đó rồi, nhưng mà tạm thời mình chưa thể khắc phục được, bạn theo dõi bên cột trạng thái, nếu nó là "Tải xong" thì có nghĩ là hoàn tất.
