### ISSUE TITLE
Phần mềm hay bị lỗi ngừng chương trình (close program) trên windows 8.1

### ISSUE THREAD

**Issue by ddnguyen122** [thangdc/Album-Downloader#21]
Khi mình click vào nút lấy bài hát từ album thì hay bị lỗi close program từ windows. Mong bạn khắc phục lỗi này, còn lại thì mình thấy rất tốt. Cảm ơn bạn vì đã tạo ra 1 phần mềm rất tuyệt.

**Comment by thangdc** [comment]
có thể là có 1 album nào đó gây ra lỗi, mình sẽ hạn chế nó, còn để khắc phục nếu bạn có thể cho mình album mà nó thường gây ra lỗi thì tốt quá, thank bạn đã thông báo, do không có email thông báo nên đến giờ mình mới biết là có nhiều người báo lỗi đến vậy

**Comment by thangdc** [comment]
Mình đã khắc phục trong bản 1.4.0.9, bạn thử download bản mới về rồi thử lại xem còn bị không nha
