### ISSUE TITLE
Tải nhạc trên trang chiasenhac.com

### ISSUE THREAD

**Issue by ddnguyen122** [thangdc/Album-Downloader#22]
Phần mềm phiên bản hiện tại có thề "thêm album" và hiện ra danh sách nhưng khi chọn album để "lấy bài hát" thì không hiện ra danh sách để down về. Mong bạn xem và khắc phục.

Thêm nữa là cần cải thiện tính ổn định do pm hay bị tự tắt khi chọn lệnh "lấy bài hát" từ playlist của trang nhaccuatui.

**Comment by thangdc** [comment]
ok bạn, mình sẽ kiểm tra và khắc phục ngay khi có thể, cảm ơn bạn đã thông báo

**Comment by thangdc** [comment]
bạn thử lại trên phiên bản 1.4.0.9 mình vừa cập nhật xem có bị không nhé, nếu còn bị bạn mở lại cái ticket này, kèm theo đó là link album mà bạn gặp vấn đề để mình xử lý nha, mong phản hồi của bạn.

**Comment by ivinix** [comment]
Không download được bạn ơi. Sau khi gửi IDM nó chỉ tải về file html.
Mình dùng version 1.4.0.9 hay 1.4.1.4 đều không down được :(

**Comment by ivinix** [comment]
Link album:
http://playlist.chiasenhac.com/nghe-album/hoa-no-ve-dem~le-quyen~1466403.html
Mình muốn download định dạng m4a 500kbps

**Comment by thangdc** [comment]
ok, mình sẽ kiểm tra lại

**Comment by thangdc** [comment]
để tải nhạc chất lượng cao bạn vui lòng nhập thông tin tài khoản chiasenhac trong phần cấu hình rồi thử lại giúp mình nhé.

**Comment by ivinix** [comment]
Vẫn không được bạn ơi. Mình thử với phiên bản mới nhất Album-Downloader-1.4.1.5 vẫn không được.

**Comment by thangdc** [comment]
Mình vẫn tải bình thường mà ta đây là một số hình ảnh của phần mềm Album Downloader 1.4.1.5:
1. Phần cấu hình mình chọn tải nhạc chất lượng cao trên chiasenhac, nhập tài khoản và chọn chất lượng 500kbps

![album-downloader-config](https://cloud.githubusercontent.com/assets/1168970/9973509/6874a7ba-5e9e-11e5-834a-e8835ae059fc.png)

2. Danh sách các album sau khi lấy về

![album-downloader-list-song](https://cloud.githubusercontent.com/assets/1168970/9973528/ad4d9af4-5e9e-11e5-9fa4-f913d227a371.png)

3. Sau khi tải về

![hoa-no-ve-dem](https://cloud.githubusercontent.com/assets/1168970/9973535/d1bc0e16-5e9e-11e5-8724-040081a28c40.png)

**Comment by ivinix** [comment]
Mình down được rồi bạn nhé. Tự nhiên down được chứ mình cũng không chỉnh lại gì hết á.
Cảm ơn tác giả nhiều nhé.
