### ISSUE TITLE
Tải album trên nhachoatau.info

### ISSUE THREAD

**Issue by ddnguyen122** [thangdc/Album-Downloader#23]
Khi Thêm album thì thấy list đủ bài nhưng khi Lấy danh sách bài hát thì lâu lâu bị thiếu bài trong album đó. Cụ thể là link này: http://www.nhachoatau.info/the-loai/nhac-thien-meditation/nhac-thien-hoa-sen-nuoc-chay.html

**Comment by thangdc** [comment]
Thanks bạn, mình sẽ kiểm tra lại rồi thông báo cho bạn sau, nhưng theo mô tả mình nghĩ là do một trong những link trong album bị lỗi nên chương trình không tải được, khi lúc lấy bài hát thì chương trình chỉ lấy tên trong danh sách nên lúc nào cũng đầy đủ, còn khi lấy bài hát thì lúc đó chương trình mới bắt đầu lấy link bài hát thực sự lúc đó nó danh sách lúc đầu và lúc này sẽ không giống nhau nữa, mình gặp lỗi này tương tự cho mp3.zing.vn, khắc phục bằng cách lấy lại bài hát thêm lần nữa.
