### ISSUE TITLE
Nhạc Số

### ISSUE THREAD

**Issue by googlesky** [thangdc/Album-Downloader#25]
Download nhạc số không được nữa :(

**Comment by thangdc** [comment]
Vẫn lấy bình thường nha bạn, mình kiểm tra trên phiên bản 1.4.1.1.

**Comment by googlesky** [comment]
À. đúng là vẫn được... tại mình test link này: 
http://nhacso.net/nghe-playlist/lien-khuc-tuan-vu.X11ZUUBa.html
Không được :) có thể do nhạc cũ. Chứ các album mới đều ngon

**Comment by thangdc** [comment]
ok, tại mình không thể kiểm tra hết các link nên có thể một số cái không lấy được, mình sẽ check lại rồi thông báo lại cho bạn sau.

**Comment by thangdc** [comment]
Mình đã fix lỗi không tải được những album như bạn gửi cho mình, bạn đợi phiên bản 1.4.1.3 sẽ có nha.
Nếu có vấn đề gì nữa bạn cung cấp thông tin như thế này cho mình sẽ dễ cho mình tìm nguyên nhân hơn.
Cảm ơn bạn,.
