### ISSUE TITLE
Trạng thái khi download 

### ISSUE THREAD

**Issue by tdchien** [thangdc/Album-Downloader#26]
Mình nhận thấy phần trạng thái khi download bài hát bằng thành phần sẵn có của phần mềm cập nhật không chính xác. Đúng hơn là không cập nhật trạng thái khi bài hát đã tải xong. Mình kiểm tra thì các bài hát tải về xong rồi nhưng phần trạng thái chỉ hiện mấy bài đầu ở mấy %.

Hiện mình đang dùng win 7 x86
Đây là hình ảnh mình sử dụng ở máy mình : http://prntscr.com/7lvar9
Phiên bản phần mềm là : 1.4.1.1

**Comment by thangdc** [comment]
Mình thấy issue đó rồi, thật ra thì nó đã tải rồi, nhưng mà trạng thái vẫn chưa được cập nhật, mình sẽ fix lỗi đó, thank bạn đã thông báo.

**Comment by thangdc** [comment]
Đã fix xong
