### ISSUE TITLE
Không thể lấy toàn bộ các bài hát từ các danh sách sau v.1.4.1.0

### ISSUE THREAD

**Issue by pkk08** [thangdc/Album-Downloader#27]
1. http://www.nhaccuatui.com/playlist/bo-tu-hoan-hao-nhac-tien-chien-cua-tui-tuan-ngoc-ft-si-phu-ft-duy-quang-ft-elvis-phuong.1daEqwSZP4sM.html
2. http://www.nhaccuatui.com/playlist/tuyet-pham-song-ca-nhac-tien-chien-va.3KjWYYq2eWth.html

**Comment by thangdc** [comment]
Minh da fix xong, phien ban 1.4.1.4 se co day du album ban nhe.
