### ISSUE TITLE
Lỗi không tải được album trên nhacso.net

### ISSUE THREAD

**Issue by 3597dxta** [thangdc/Album-Downloader#28]
Lỗi không tải được playlist trên nhacso.net, album thì tải đc còn playlist bị lỗi khi nhấn lấy bài hát nó ko hiện gì cả

**Comment by thangdc** [comment]
Mình vừa fix lỗi đó rồi, bạn đợi phiên bản mới rồi kiểm tra lại giúp mình nhé. Nếu còn bị thì bạn mở lại cái issue này giúp mình. Không biết lỗi này có giống với lỗi một bạn đã báo cho mình qua group trên facebook hay không, nếu có thể bạn cho mình liên kiết đến album đó thì càng tốt.
