### ISSUE TITLE
error when I get songs with high quality options

### ISSUE THREAD

**Issue by chikaro24** [thangdc/Album-Downloader#29]
![screenshot 4](https://cloud.githubusercontent.com/assets/5095778/9160664/918b42d2-3f66-11e5-8d8e-329fa3f4feda.png)

**Comment by thangdc** [comment]
ok, I will check it again

**Comment by thangdc** [comment]
You cannot download this album because the copyright of these song not allow to download, so I can only fixed it to not stop the application.

**Comment by thangdc** [comment]
Fixed, but can not donwload high quality song, just normal song.
