### ISSUE TITLE
from Tai Tran

### ISSUE THREAD

**Issue by trantai** [thangdc/Album-Downloader#30]
Dễ quạo ghê, không tải đc album nào hết!
Mình ở Mỹ, có liên quan gì không?

http://www.nhaccuatui.com/playlist/nhac-hoa-tau-hay-nhat-moi-thoi-dai-va.W1RhBaaq44oQ.html
http://www.nhaccuatui.com/chu-de/nhac-hoa-tau-tuyen-chon.weotltzru.html
http://www.nhaccuatui.com/playlist/tuyen-tap-ca-khuc-edm-soi-dong-nhat-vol-1-dj.3bThgOGqqZ4j.html

**Comment by trantai** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/11264734/9374095/a8a62ab2-46bf-11e5-902b-fb65d5bd744c.jpg)

**Comment by thangdc** [comment]
Mình sẽ kiểm tra và fix lại, cảm ơn bạn đã báo cáo

**Comment by thangdc** [comment]
Đã fix xong, hiện tại nhaccuatui.com không cho tải nhạc chất lượng cao, nên bạn vào phần cấu hình chọn lại tải nhạc bình thường sẽ được, bản 1.4.1.5 sẽ fix lỗi bị crash
