### ISSUE TITLE
link

### ISSUE THREAD

**Issue by trantai** [thangdc/Album-Downloader#34]
http://www.nhaccuatui.com/playlist/tuyen-tap-ca-khuc-hay-nhat-cua-ladykillah-va.T1Eum4od5BH7.html

**Comment by thangdc** [comment]
Mình thử kiếm tra bản mới với cấu hình là chất lượng bình thường vẫn tải được, bạn tải nhạc chất lượng cao ah?

![album-downloader-1 4 1 5-issue](https://cloud.githubusercontent.com/assets/1168970/9427622/999bd1d0-49b1-11e5-98c0-af833f1b5362.png)
