### ISSUE TITLE
Download album từ mp3.zing.vn

### ISSUE THREAD

**Issue by quannh-uet** [thangdc/Album-Downloader#35]
Chào bạn, hiện tại mình thử tải album trên mp3.zing.vn về nhưng gặp lỗi như sau:
- Chọn "Thêm album": danh sách bài hát được hiển thị trong màn hình con "Thêm album".
- Chọn album sau đó chọn "Lấy bài hát": taskbar hiển thị "Đang lấy bài hát", tab "Danh sách bài hát" được mở ra.
Lỗi: Không có bài hát trong tab "Danh sách bài hát".

Version: 1.4.1.5 giải nén từ file zip download từ địa chỉ https://bitbucket.org/thangdc/ph-n-m-m-vi-t/downloads/Album-Downloader-1.4.1.5.zip
Link album: http://mp3.zing.vn/album/Chua-Bao-Gio-Single-Trung-Quan-Idol/ZWZBFFO7.html

Mong bạn sớm khắc phục hoặc hướng dẫn mình cách download album trên zing.

Br,

**Comment by thangdc** [comment]
Vâng cảm ơn bạn đã thông báo, mình mới vừa nhận được thông báo đang fix lỗi, sẽ báo lại cho bạn tải bản mới nhất 1.4.1.6 khi xong, xin lỗi vì trả lời muộn

**Comment by thangdc** [comment]
Mình đã fix xong, bạn tải bản mới giúp mình nhé, thanks bạn

Link download: vietsofts.thangdc.com/album-downloader.html
