### ISSUE TITLE
Chương trình hiển thị lỗi Unhandled exception sau khi search phiên bản 1.4.16

### ISSUE THREAD

**Issue by phuonghd** [thangdc/Album-Downloader#36]
Ở tab tìm kiếm khi mình nhập từ khóa cần tìm kiếm, bấm nút tìm kiếm --> chương trình vẫn tìm được kết quả nhưng hiển thị lỗi unhandled exception như hình đính kèm. Mong bạn sớm fix lỗi này.
![error](https://cloud.githubusercontent.com/assets/5194827/10301259/ad7c58be-6c2a-11e5-9381-d7fb55230129.jpg)

**Comment by thangdc** [comment]
ok, mình sẽ kiểm tra lại và fix lại khi tìm được nguyên nhân, thanks bạn

**Comment by thangdc** [comment]
đã fix xong
