### ISSUE TITLE
Không tải được album woim.net

### ISSUE THREAD

**Issue by anhhoang236** [thangdc/Album-Downloader#37]
Mình add album nhưng ấn Lấy bài hát thì không ra được bài nào. Trước đó có tải được vài album thành công, giờ không được nữa, đã restart lại máy cũng ko đc. (Mình đăng nhập woim.net = premium rồi nhé).

**Comment by thangdc** [comment]
phiên bản của mình bị giới hạn, bạn chỉ tải được 5 albums một ngày thôi (vì woim.net giới hạn với những người dùng bình thường bạn nhé)
