### ISSUE TITLE
Không tải được Album từ Nhaccuatui

### ISSUE THREAD

**Issue by thaotrphuong** [thangdc/Album-Downloader#38]
Mình không thể tải được album nhạc từ nhacjcuatui nua. Các lần trước đây mình làm đều thành công. Không thấy hiện thông báo lỗi gì.

**Comment by thangdc** [comment]
Vâng mình sẽ kiểm tra nhưng mà nếu bạn có link album mà bạn không tải được thì mình vô cùng biết ơn

**Comment by thangdc** [comment]
Đã tải được rồi, bạn dùng bản mới nhất nha.
