### ISSUE TITLE
Ten album

### ISSUE THREAD

**Issue by album32** [thangdc/Album-Downloader#40]
Tên thư mục : Bổ sung Tên album + Tên ca sỹ nữa là ok. VD : Anh Nho Em Nhieu - Du Thien.

**Comment by thangdc** [comment]
nhưng mà nếu trong album có nhiều ca sỹ thì sẽ như thế nào ta

**Comment by thangdc** [comment]
tại vì mỗi album có thể có nhiều ca sỹ nên mình không thể update được, cảm ơn bạn.
