### ISSUE TITLE
Lỗi "Windows has stopped working"

### ISSUE THREAD

**Issue by khangta1494** [thangdc/Album-Downloader#41]
Phần mềm rất hay, cám ơn bạn đã chia sẻ! Mong bạn tiếp tục cập nhật, chỉnh sửa phần mềm và phát huy hơn nữa.
- Khi chọn Album bất kỳ từ trang "Chiasenhac" và "Lấy bài hát" thì xuất hiện lỗi "Windows has stopped working", buộc phải nhấn "Close" và chương trình thoát hoàn toàn (không còn chạy nền).
- Ngoài ra, trong quá trình tìm kiếm đang chạy, khi bấm "Dừng tìm kiếm" thì chương trình bị đơ (treo) không thể thao tác gì được, buộc phải End Task để đóng chương trình.

Phiên bản: 1.4.1.9

![image](https://cloud.githubusercontent.com/assets/20461492/16845919/b91836ac-4a14-11e6-8610-3672693e740f.png)

**Comment by thangdc** [comment]
Vâng mình sẽ kiểm tra lại và fix lỗi này, xin cảm ơn đã cung cấp thông tin cho mình, nhưng mà bạn có thể cho mình link album được không? trong hình thì không đủ thông tin về album mà bạn gặp vấn đề

**Comment by khangta1494** [comment]
Album mình cần down hiện có 2 phần.
Vừa rồi mình đã update p.mềm lên ver mới nhưng vẫn bị lỗi "stop working"
khi lấy d.sách bài hát từ album này.

Link:
http://chiasenhac.vn/nghe-album/welcome-to-maplestory~maplestory~ts35zs06qh14nk.html

Mình thấy p.mềm rất hay, nhưng còn khá nhiều lỗi. Mong bạn cố gắng phát
triển thêm.

**Comment by thangdc** [comment]
Vâng cảm ơn bạn đã cung cấp thông tin chi tiết, mình sẽ fix lỗi này trong bản cập nhật tiếp theo

**Comment by thangdc** [comment]
hiện nay chức năng tìm kiếm không còn được hỗ trợ.
