### ISSUE TITLE
ko lấy đc bài hát từ 1 số link trên nhaccuatui.

### ISSUE THREAD

**Issue by johnnyle7** [thangdc/Album-Downloader#42]
Ad xem giúp mình sao mình add album vào đc nhưng khi lấy bài hát thì ko thấy bài nào. 
http://www.nhaccuatui.com/playlist/nhac-viet-hot-thang-7-va.51NdC2Kjj4Eo.html?st=2

**Comment by baoduy** [comment]
minh cung khong download dc

**Comment by johnnyle7** [comment]
Ko biết là do link hay do NCT nó update j để chặn phần mềm. Cái đc cái ko,
phần lớn là ko bắt đc chứ ko phải mình cái này. Hix.

**Comment by thangbinh** [comment]
version 1.4.6 down dc nhung ko lay dc ten album

**Comment by thangdc** [comment]
cảm ơn bạn đã cung cấp thông tin, mình sẽ kiểm tra và cập nhật khi phát hiện vấn đề

**Comment by thangdc** [comment]
Mình kiểm tra link của bạn cung cấp với phiên bản 1.4.2.0, thì nó vẫn lấy được 47 bài mà ta

**Comment by johnnyle7** [comment]
mình dùng win 10, thử lại vẫn ko thấy bài hát nào.

**Comment by thangdc** [comment]
Hay bạn thử version mới xem có bị tình trạng tương tự hok: http://www.thangdc.com/2016/08/cap-nhat-album-downloader-1421.html

**Comment by johnnyle7** [comment]
Mình thử cái mới nhưng nhạc cũng chỉ 3.x mb thì chắc cũng chỉ 128bit thôi. thế thì bản cũ vẫn down đc. bản cũ chỉ ko tìm thấy bài hát khi setting trong cấu hình là tải nhạc chất lượng cao thôi.

**Comment by thangdc** [comment]
ah, nhạc chất lượng cao bên nhaccuatui.com hiện tại không còn lấy được nữa, nên chỉ có thể tải được nhạc 128kbps thôi.
