### ISSUE TITLE
không lấy được bài hát trên site nhaccuatui

### ISSUE THREAD

**Issue by thangbinh** [thangdc/Album-Downloader#43]
Khi thêm album, thì trong danh sách album vẫn hiện ra tên album nhưng tab bài hát thì lại trống trơn, ko hiển thị thông tin gì cả. Mong tác giả fix lại vấn đề này. Cảm ơn

**Comment by thangdc** [comment]
bạn vui lòng cung cấp thêm thông tin, ví dụ như link album mà bạn gặp lỗi.
xin lỗi vì đã trả lời trễ, mình sẽ kiểm tra lại
