### ISSUE TITLE
mình ko lấy đc danh sách bài hát của trang zing

### ISSUE THREAD

**Issue by 1995duynguyen** [thangdc/Album-Downloader#44]
http://mp3.zing.vn/album/Nhac-Danh-Cho-Game-Thu-Various-Artists/ZOU0BI0B.html

**Comment by thangdc** [comment]
Vâng mình đã phát hiện ra vấn đề rồi, cảm bạn đã cung cấp thông tin, mình sẽ update trong bản cập nhật  kế tiếp.

**Comment by 1995duynguyen** [comment]
hình như phần album của cả trang zing lỗi hết rồi ý. mình xem các album khác cx không lấy đc ds bài hát đâu

**Comment by thangdc** [comment]
đúng rồi đó bạn, mình đã có cách khắc phục rồi, bạn chờ bản 1.4.2.1 nha, phiên bản thử nghiệm mới có nhiều thay đổi so với bản trước.
