### ISSUE TITLE
Không tải được ở Youtube

### ISSUE THREAD

**Issue by FrankyVN** [thangdc/Album-Downloader#45]
Mình vẫn download các bài hát/album ở ZING hoặc Nhaccuatui vẫn bình thường, chỉ có Youtube là bị lỗi như thiếu .net framework.
Hiện tại mình đang sử dụng WIN 10 và đã cập nhật các bản .net framework 4.6.2.
Mong bạn hướng dẫn cách khắc phục
THANKS!
![untitled](https://cloud.githubusercontent.com/assets/22273083/18614761/5f521f82-7dbf-11e6-805c-450f90f99f83.png)

**Comment by thangdc** [comment]
Mình sẽ kiểm tra lại, cảm ơn bạn đã thông báo.

**Comment by thangdc** [comment]
Đã fix trong bản mới, bạn kiểm tra lại giúp mình nha, cảm ơn.

**Comment by FrankyVN** [comment]
Vâng mình sẽ test trong tgian sớm nhất. Cảm ơn bạn đã cho ra đời một ứng
dụng hữu ích. Thanks!

**Comment by FrankyVN** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22273083/21217039/ba7d659e-c2dc-11e6-87b4-9e3d7d6b13a4.png)
Khi chuyển link qua IDM để download thì nó sẽ tạo rất nhiều thư mục con trước khi đến được bài hát cần nghe. Một ablum 100 bài cần mở hơn 100 thư mục để lấy bài hát rất tốn nhiều thời gian k cần thiết. Cảm ơn bạn đã quan tâm thắc mắc của mình.
THANKS!!!

**Comment by thangdc** [comment]
Bạn vui lòng cung cấp link mà gây ra issue này để mình check nha.

**Comment by FrankyVN** [comment]
Mình đã thử lại với link ablum khác của mp3.zing.vn vẫn thấy lỗi tạo nhiều Folder trên!
Link thử nghiệm: http://mp3.zing.vn/album/Bang-Xep-Hang-Bai-Hat-Viet-Nam-Tuan-52-2016/ZOUAAUFI.html
![image](https://cloud.githubusercontent.com/assets/22273083/21750891/870ad134-d5f0-11e6-9f2b-b6dbf6b944e7.png)

**Comment by thangdc** [comment]
Minh vua kiem tra thi thay no van tai binh thuong, minh k hieu tai sao ben ban lai bi nua. Ban bi loi la luc gui qua IDM ah? Minh tai bang chuong trinh thi khong bi.

![albumdownloader](https://cloud.githubusercontent.com/assets/1168970/21809804/c9f73334-d77b-11e6-97b0-084308ab7bce.png)

**Comment by FrankyVN** [comment]
Mình cũng k rõ nguyên nhân tại đâu, hiện tại mình đang sử dụng WIN 10 và IDM cả 2 đều update đầy đủ.  Tạm thời mình khắc phục bằng cách, nhập "*.mp3" trong ô tìm kiếm của folder để lấy link nhạc và chép sang 1 folder khác. Nói chung k mất nhiều thời gian cho bước này nhưng nếu tìm ra dc nguyên nhân tự tạo ra nhiều folder MP3 thì hay quá ;)

**Comment by thangdc** [comment]
Ok, mình sẽ check lại lần nữa xem có thể giải quyết được không, rồi sẽ cập nhật lại với bạn sau.

**Comment by thangdc** [comment]
Cuối cùng cũng đã tìm được nguyên nhân và cách khắc phục, bạn tải bản mới về sẽ hết bị nha.
link download: vietsofts.thangdc.com/album-downloader.html

**Comment by FrankyVN** [comment]
Cảm ơn bạn đã FIX lỗi ;)
