### ISSUE TITLE
Khong download dc Zing Album

### ISSUE THREAD

**Issue by HungLanChi** [thangdc/Album-Downloader#46]
http://mp3.zing.vn/album/Today-s-Top-Hits-Various-Artists/ZWZC0WCE.html

Dung album downloader khong tim dc cac bai hat cua album de download ve
![image](https://cloud.githubusercontent.com/assets/29179339/26763678/08e46446-4981-11e7-8577-735ecc40592a.png)
![image](https://cloud.githubusercontent.com/assets/29179339/26763691/21b00728-4981-11e7-8829-d5a7c5f84060.png)

**Comment by thangdc** [comment]
Bạn tải bản mới giúp mình nha.
