### ISSUE TITLE
Lỗi khi tải danh sách bài hát

### ISSUE THREAD

**Issue by hoangnamitc** [thangdc/Album-Downloader#48]
Hi @thangdc ,

Tôi gặp lỗi như sau khi tải 1 album tại nhac.vn. nhờ @thangdc  xem giúp.

OS: Windows 10 x64

![downlload](https://user-images.githubusercontent.com/7042462/32526973-b157a0cc-c45e-11e7-99f1-7fc5c27716ad.gif)

**Comment by thangdc** [comment]
ok, để mình check lại

**Comment by thangdc** [comment]
Đã fix xong, bạn tải bản mới về là hết bị nha.
